# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ads.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'ads.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tads.proto\x12\x03\x61\x64s\"\xbe\x01\n\x0cRealEstateAd\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t\x12\x17\n\x0fproperty_id_nma\x18\x05 \x01(\t\x12\r\n\x05price\x18\x06 \x01(\x01\x12\x0c\n\x04type\x18\x07 \x01(\t\x12\x0e\n\x06status\x18\x08 \x01(\t\x12\x14\n\x0cphone_number\x18\t \x01(\t\x12\x11\n\tlisted_by\x18\n \x01(\t\"L\n\x0fSingleAdRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x17\n\x0fproperty_id_nma\x18\x02 \x01(\t\x12\x14\n\x0cphone_number\x18\x03 \x01(\t\"5\n\x0fOwnedAdsRequest\x12\x14\n\x0cphone_number\x18\x01 \x01(\t\x12\x0c\n\x04page\x18\x02 \x01(\x05\"}\n\x10\x46ilterAdsRequest\x12\x17\n\x0fproperty_id_nma\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x11\n\tmin_price\x18\x04 \x01(\x01\x12\x11\n\tmax_price\x18\x05 \x01(\x01\x12\x0c\n\x04page\x18\x06 \x01(\x05\"5\n\x13MultipleAdsResponse\x12\x1e\n\x03\x61\x64s\x18\x01 \x03(\x0b\x32\x11.ads.RealEstateAd\"!\n\x0eStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1e\n\rCountResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x32\x81\x04\n\tAdService\x12\x30\n\x08\x43reateAd\x12\x11.ads.RealEstateAd\x1a\x11.ads.RealEstateAd\x12\x30\n\x05GetAd\x12\x14.ads.SingleAdRequest\x1a\x11.ads.RealEstateAd\x12\x39\n\x06GetAds\x12\x15.ads.FilterAdsRequest\x1a\x18.ads.MultipleAdsResponse\x12\x35\n\x08\x43ountAds\x12\x15.ads.FilterAdsRequest\x1a\x12.ads.CountResponse\x12=\n\x0bGetOwnedAds\x12\x14.ads.OwnedAdsRequest\x1a\x18.ads.MultipleAdsResponse\x12\x39\n\rCountOwnedAds\x12\x14.ads.OwnedAdsRequest\x1a\x12.ads.CountResponse\x12\x30\n\x08UpdateAd\x12\x11.ads.RealEstateAd\x1a\x11.ads.RealEstateAd\x12\x35\n\x08\x44\x65leteAd\x12\x14.ads.SingleAdRequest\x1a\x13.ads.StatusResponse\x12;\n\x0eHasWriteAccess\x12\x14.ads.SingleAdRequest\x1a\x13.ads.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ads_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REALESTATEAD']._serialized_start=19
  _globals['_REALESTATEAD']._serialized_end=209
  _globals['_SINGLEADREQUEST']._serialized_start=211
  _globals['_SINGLEADREQUEST']._serialized_end=287
  _globals['_OWNEDADSREQUEST']._serialized_start=289
  _globals['_OWNEDADSREQUEST']._serialized_end=342
  _globals['_FILTERADSREQUEST']._serialized_start=344
  _globals['_FILTERADSREQUEST']._serialized_end=469
  _globals['_MULTIPLEADSRESPONSE']._serialized_start=471
  _globals['_MULTIPLEADSRESPONSE']._serialized_end=524
  _globals['_STATUSRESPONSE']._serialized_start=526
  _globals['_STATUSRESPONSE']._serialized_end=559
  _globals['_COUNTRESPONSE']._serialized_start=561
  _globals['_COUNTRESPONSE']._serialized_end=591
  _globals['_ADSERVICE']._serialized_start=594
  _globals['_ADSERVICE']._serialized_end=1107
# @@protoc_insertion_point(module_scope)
