# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"&\n\x0eSendOtpRequest\x12\x14\n\x0cphone_number\x18\x01 \x01(\t\"3\n\x0fNoTokenResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"B\n\x0fRegisterRequest\x12\x14\n\x0cphone_number\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03otp\x18\x03 \x01(\t\"1\n\x0cLoginRequest\x12\x14\n\x0cphone_number\x18\x01 \x01(\t\x12\x0b\n\x03otp\x18\x02 \x01(\t\"@\n\rTokenResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t\" \n\x0fValidateRequest\x12\r\n\x05token\x18\x01 \x01(\t\"\'\n\x10ValidateResponse\x12\x13\n\x0bpermissions\x18\x01 \x03(\t2\xea\x01\n\x0b\x41uthService\x12\x36\n\x07SendOtp\x12\x14.auth.SendOtpRequest\x1a\x15.auth.NoTokenResponse\x12\x36\n\x08Register\x12\x15.auth.RegisterRequest\x1a\x13.auth.TokenResponse\x12\x30\n\x05Login\x12\x12.auth.LoginRequest\x1a\x13.auth.TokenResponse\x12\x39\n\x08Validate\x12\x15.auth.ValidateRequest\x1a\x16.auth.ValidateResponseB\x11Z\x0f./proto;serviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\017./proto;service'
  _globals['_SENDOTPREQUEST']._serialized_start=20
  _globals['_SENDOTPREQUEST']._serialized_end=58
  _globals['_NOTOKENRESPONSE']._serialized_start=60
  _globals['_NOTOKENRESPONSE']._serialized_end=111
  _globals['_REGISTERREQUEST']._serialized_start=113
  _globals['_REGISTERREQUEST']._serialized_end=179
  _globals['_LOGINREQUEST']._serialized_start=181
  _globals['_LOGINREQUEST']._serialized_end=230
  _globals['_TOKENRESPONSE']._serialized_start=232
  _globals['_TOKENRESPONSE']._serialized_end=296
  _globals['_VALIDATEREQUEST']._serialized_start=298
  _globals['_VALIDATEREQUEST']._serialized_end=330
  _globals['_VALIDATERESPONSE']._serialized_start=332
  _globals['_VALIDATERESPONSE']._serialized_end=371
  _globals['_AUTHSERVICE']._serialized_start=374
  _globals['_AUTHSERVICE']._serialized_end=608
# @@protoc_insertion_point(module_scope)
