# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import server.pb.properties_pb2 as properties__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in properties_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PropertyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchProperties = channel.unary_unary(
                '/realestate.PropertyService/SearchProperties',
                request_serializer=properties__pb2.FilterPropertyRequest.SerializeToString,
                response_deserializer=properties__pb2.Response.FromString,
                _registered_method=True)
        self.CountProperties = channel.unary_unary(
                '/realestate.PropertyService/CountProperties',
                request_serializer=properties__pb2.FilterPropertyRequest.SerializeToString,
                response_deserializer=properties__pb2.Response.FromString,
                _registered_method=True)
        self.GetProperty = channel.unary_unary(
                '/realestate.PropertyService/GetProperty',
                request_serializer=properties__pb2.SinglePropertyRequest.SerializeToString,
                response_deserializer=properties__pb2.Response.FromString,
                _registered_method=True)
        self.GetPropertyUnits = channel.unary_unary(
                '/realestate.PropertyService/GetPropertyUnits',
                request_serializer=properties__pb2.PropertyUnitsRequest.SerializeToString,
                response_deserializer=properties__pb2.Response.FromString,
                _registered_method=True)
        self.CountPropertyUnits = channel.unary_unary(
                '/realestate.PropertyService/CountPropertyUnits',
                request_serializer=properties__pb2.PropertyUnitsRequest.SerializeToString,
                response_deserializer=properties__pb2.Response.FromString,
                _registered_method=True)
        self.GetUnit = channel.unary_unary(
                '/realestate.PropertyService/GetUnit',
                request_serializer=properties__pb2.SingleUnitRequest.SerializeToString,
                response_deserializer=properties__pb2.Response.FromString,
                _registered_method=True)
        self.GetOwnedProperties = channel.unary_unary(
                '/realestate.PropertyService/GetOwnedProperties',
                request_serializer=properties__pb2.OwnedItemsRequest.SerializeToString,
                response_deserializer=properties__pb2.Response.FromString,
                _registered_method=True)
        self.CountOwnedProperties = channel.unary_unary(
                '/realestate.PropertyService/CountOwnedProperties',
                request_serializer=properties__pb2.OwnedItemsRequest.SerializeToString,
                response_deserializer=properties__pb2.Response.FromString,
                _registered_method=True)
        self.GetHistoricValuations = channel.unary_unary(
                '/realestate.PropertyService/GetHistoricValuations',
                request_serializer=properties__pb2.SingleUnitRequest.SerializeToString,
                response_deserializer=properties__pb2.Response.FromString,
                _registered_method=True)


class PropertyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SearchProperties(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountProperties(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPropertyUnits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountPropertyUnits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUnit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOwnedProperties(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountOwnedProperties(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistoricValuations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PropertyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchProperties': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchProperties,
                    request_deserializer=properties__pb2.FilterPropertyRequest.FromString,
                    response_serializer=properties__pb2.Response.SerializeToString,
            ),
            'CountProperties': grpc.unary_unary_rpc_method_handler(
                    servicer.CountProperties,
                    request_deserializer=properties__pb2.FilterPropertyRequest.FromString,
                    response_serializer=properties__pb2.Response.SerializeToString,
            ),
            'GetProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProperty,
                    request_deserializer=properties__pb2.SinglePropertyRequest.FromString,
                    response_serializer=properties__pb2.Response.SerializeToString,
            ),
            'GetPropertyUnits': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPropertyUnits,
                    request_deserializer=properties__pb2.PropertyUnitsRequest.FromString,
                    response_serializer=properties__pb2.Response.SerializeToString,
            ),
            'CountPropertyUnits': grpc.unary_unary_rpc_method_handler(
                    servicer.CountPropertyUnits,
                    request_deserializer=properties__pb2.PropertyUnitsRequest.FromString,
                    response_serializer=properties__pb2.Response.SerializeToString,
            ),
            'GetUnit': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUnit,
                    request_deserializer=properties__pb2.SingleUnitRequest.FromString,
                    response_serializer=properties__pb2.Response.SerializeToString,
            ),
            'GetOwnedProperties': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOwnedProperties,
                    request_deserializer=properties__pb2.OwnedItemsRequest.FromString,
                    response_serializer=properties__pb2.Response.SerializeToString,
            ),
            'CountOwnedProperties': grpc.unary_unary_rpc_method_handler(
                    servicer.CountOwnedProperties,
                    request_deserializer=properties__pb2.OwnedItemsRequest.FromString,
                    response_serializer=properties__pb2.Response.SerializeToString,
            ),
            'GetHistoricValuations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistoricValuations,
                    request_deserializer=properties__pb2.SingleUnitRequest.FromString,
                    response_serializer=properties__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'realestate.PropertyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('realestate.PropertyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PropertyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SearchProperties(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/realestate.PropertyService/SearchProperties',
            properties__pb2.FilterPropertyRequest.SerializeToString,
            properties__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountProperties(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/realestate.PropertyService/CountProperties',
            properties__pb2.FilterPropertyRequest.SerializeToString,
            properties__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/realestate.PropertyService/GetProperty',
            properties__pb2.SinglePropertyRequest.SerializeToString,
            properties__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPropertyUnits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/realestate.PropertyService/GetPropertyUnits',
            properties__pb2.PropertyUnitsRequest.SerializeToString,
            properties__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountPropertyUnits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/realestate.PropertyService/CountPropertyUnits',
            properties__pb2.PropertyUnitsRequest.SerializeToString,
            properties__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUnit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/realestate.PropertyService/GetUnit',
            properties__pb2.SingleUnitRequest.SerializeToString,
            properties__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOwnedProperties(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/realestate.PropertyService/GetOwnedProperties',
            properties__pb2.OwnedItemsRequest.SerializeToString,
            properties__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountOwnedProperties(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/realestate.PropertyService/CountOwnedProperties',
            properties__pb2.OwnedItemsRequest.SerializeToString,
            properties__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistoricValuations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/realestate.PropertyService/GetHistoricValuations',
            properties__pb2.SingleUnitRequest.SerializeToString,
            properties__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
