# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import server.pb.valuation_pb2 as valuation__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in valuation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ValuationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPropertyValuation = channel.unary_unary(
                '/valuation.ValuationService/GetPropertyValuation',
                request_serializer=valuation__pb2.PropertyValuationRequest.SerializeToString,
                response_deserializer=valuation__pb2.ValuationResponse.FromString,
                _registered_method=True)
        self.GetUnitValuation = channel.unary_unary(
                '/valuation.ValuationService/GetUnitValuation',
                request_serializer=valuation__pb2.UnitValuationRequest.SerializeToString,
                response_deserializer=valuation__pb2.ValuationResponse.FromString,
                _registered_method=True)


class ValuationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPropertyValuation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUnitValuation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ValuationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPropertyValuation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPropertyValuation,
                    request_deserializer=valuation__pb2.PropertyValuationRequest.FromString,
                    response_serializer=valuation__pb2.ValuationResponse.SerializeToString,
            ),
            'GetUnitValuation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUnitValuation,
                    request_deserializer=valuation__pb2.UnitValuationRequest.FromString,
                    response_serializer=valuation__pb2.ValuationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'valuation.ValuationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('valuation.ValuationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ValuationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPropertyValuation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/valuation.ValuationService/GetPropertyValuation',
            valuation__pb2.PropertyValuationRequest.SerializeToString,
            valuation__pb2.ValuationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUnitValuation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/valuation.ValuationService/GetUnitValuation',
            valuation__pb2.UnitValuationRequest.SerializeToString,
            valuation__pb2.ValuationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
