# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: valuation.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'valuation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fvaluation.proto\x12\tvaluation\"A\n\x18PropertyValuationRequest\x12\x17\n\x0fproperty_id_nma\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\"5\n\x14UnitValuationRequest\x12\x0f\n\x07unit_id\x18\x01 \x01(\x03\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\"\'\n\x11ValuationResponse\x12\x12\n\nvaluations\x18\x01 \x01(\t2\xc4\x01\n\x10ValuationService\x12[\n\x14GetPropertyValuation\x12#.valuation.PropertyValuationRequest\x1a\x1c.valuation.ValuationResponse\"\x00\x12S\n\x10GetUnitValuation\x12\x1f.valuation.UnitValuationRequest\x1a\x1c.valuation.ValuationResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'valuation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROPERTYVALUATIONREQUEST']._serialized_start=30
  _globals['_PROPERTYVALUATIONREQUEST']._serialized_end=95
  _globals['_UNITVALUATIONREQUEST']._serialized_start=97
  _globals['_UNITVALUATIONREQUEST']._serialized_end=150
  _globals['_VALUATIONRESPONSE']._serialized_start=152
  _globals['_VALUATIONRESPONSE']._serialized_end=191
  _globals['_VALUATIONSERVICE']._serialized_start=194
  _globals['_VALUATIONSERVICE']._serialized_end=390
# @@protoc_insertion_point(module_scope)
